<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $permissions = [
            // Dashboard Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Dashboard',
                'slug' => 'dashboard.view',
                'description' => 'Access and view the dashboard',
                'module' => 'dashboard',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Products Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Products',
                'slug' => 'products.view',
                'description' => 'View list of products',
                'module' => 'products',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Products',
                'slug' => 'products.create',
                'description' => 'Create new products',
                'module' => 'products',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Products',
                'slug' => 'products.update',
                'description' => 'Edit existing products',
                'module' => 'products',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Products',
                'slug' => 'products.delete',
                'description' => 'Delete products',
                'module' => 'products',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Manage Product Pricing',
                'slug' => 'products.pricing',
                'description' => 'Manage product pricing',
                'module' => 'products',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Brands Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Brands',
                'slug' => 'brands.view',
                'description' => 'View list of brands',
                'module' => 'brands',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Brands',
                'slug' => 'brands.create',
                'description' => 'Create new brands',
                'module' => 'brands',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Brands',
                'slug' => 'brands.update',
                'description' => 'Edit existing brands',
                'module' => 'brands',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Brands',
                'slug' => 'brands.delete',
                'description' => 'Delete brands',
                'module' => 'brands',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Regions Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Regions',
                'slug' => 'regions.view',
                'description' => 'View list of regions',
                'module' => 'regions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Regions',
                'slug' => 'regions.create',
                'description' => 'Create new regions',
                'module' => 'regions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Regions',
                'slug' => 'regions.update',
                'description' => 'Edit existing regions',
                'module' => 'regions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Regions',
                'slug' => 'regions.delete',
                'description' => 'Delete regions',
                'module' => 'regions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Branches Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Branches',
                'slug' => 'branches.view',
                'description' => 'View list of branches',
                'module' => 'branches',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Branches',
                'slug' => 'branches.create',
                'description' => 'Create new branches',
                'module' => 'branches',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Branches',
                'slug' => 'branches.update',
                'description' => 'Edit existing branches',
                'module' => 'branches',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Branches',
                'slug' => 'branches.delete',
                'description' => 'Delete branches',
                'module' => 'branches',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Manage Branch Users',
                'slug' => 'branches.manage-users',
                'description' => 'Assign users to branches',
                'module' => 'branches',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Stock Transfers Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Stock Transfers',
                'slug' => 'stock-transfers.view',
                'description' => 'View stock transfers',
                'module' => 'stock-transfers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Stock Transfers',
                'slug' => 'stock-transfers.create',
                'description' => 'Create new stock transfers',
                'module' => 'stock-transfers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Receive Stock Transfers',
                'slug' => 'stock-transfers.receive',
                'description' => 'Receive stock transfers',
                'module' => 'stock-transfers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Cancel Stock Transfers',
                'slug' => 'stock-transfers.cancel',
                'description' => 'Cancel stock transfers',
                'module' => 'stock-transfers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Stock Management Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Stock Management',
                'slug' => 'stock-management.view',
                'description' => 'Access stock management',
                'module' => 'stock-management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Approve Stock Transfers',
                'slug' => 'stock-management.approve',
                'description' => 'Approve stock transfer requests',
                'module' => 'stock-management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Restock Products',
                'slug' => 'stock-management.restock',
                'description' => 'Restock products',
                'module' => 'stock-management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Branch Stocks Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Branch Stocks',
                'slug' => 'branch-stocks.view',
                'description' => 'View branch stock levels',
                'module' => 'branch-stocks',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Branch Stocks',
                'slug' => 'branch-stocks.create',
                'description' => 'Create branch stock entries',
                'module' => 'branch-stocks',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Branch Stocks',
                'slug' => 'branch-stocks.update',
                'description' => 'Update branch stock levels',
                'module' => 'branch-stocks',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sales Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Sales',
                'slug' => 'sales.view',
                'description' => 'View sales records',
                'module' => 'sales',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Sales',
                'slug' => 'sales.create',
                'description' => 'Create new sales',
                'module' => 'sales',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Transactions Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Transactions',
                'slug' => 'transactions.view',
                'description' => 'View transaction history',
                'module' => 'transactions',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customers Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Customers',
                'slug' => 'customers.view',
                'description' => 'View list of customers',
                'module' => 'customers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Customers',
                'slug' => 'customers.create',
                'description' => 'Create new customers',
                'module' => 'customers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Customers',
                'slug' => 'customers.update',
                'description' => 'Edit existing customers',
                'module' => 'customers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Customers',
                'slug' => 'customers.delete',
                'description' => 'Delete customers',
                'module' => 'customers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Customer Disbursements Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Customer Disbursements',
                'slug' => 'customer-disbursements.view',
                'description' => 'View customer disbursements',
                'module' => 'customer-disbursements',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Customer Disbursements',
                'slug' => 'customer-disbursements.create',
                'description' => 'Create customer disbursements',
                'module' => 'customer-disbursements',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Devices Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Devices',
                'slug' => 'devices.view',
                'description' => 'View list of devices',
                'module' => 'devices',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Devices',
                'slug' => 'devices.create',
                'description' => 'Create new devices',
                'module' => 'devices',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Devices',
                'slug' => 'devices.update',
                'description' => 'Edit existing devices',
                'module' => 'devices',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Devices',
                'slug' => 'devices.delete',
                'description' => 'Delete devices',
                'module' => 'devices',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tickets Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Tickets',
                'slug' => 'tickets.view',
                'description' => 'View support tickets',
                'module' => 'tickets',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Tickets',
                'slug' => 'tickets.create',
                'description' => 'Create new support tickets',
                'module' => 'tickets',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Tickets',
                'slug' => 'tickets.update',
                'description' => 'Update ticket information',
                'module' => 'tickets',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Reply to Tickets',
                'slug' => 'tickets.reply',
                'description' => 'Reply to support tickets',
                'module' => 'tickets',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Manage Ticket Disbursements',
                'slug' => 'tickets.disbursements',
                'description' => 'Create disbursements from tickets',
                'module' => 'tickets',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Users Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Users',
                'slug' => 'users.view',
                'description' => 'View list of users',
                'module' => 'users',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Users',
                'slug' => 'users.create',
                'description' => 'Create new users',
                'module' => 'users',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Users',
                'slug' => 'users.update',
                'description' => 'Edit existing users',
                'module' => 'users',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Users',
                'slug' => 'users.delete',
                'description' => 'Delete users',
                'module' => 'users',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Manage Field Agents',
                'slug' => 'users.manage-field-agents',
                'description' => 'Convert users to field agents',
                'module' => 'users',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Field Agents Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Field Agents',
                'slug' => 'field-agents.view',
                'description' => 'View list of field agents',
                'module' => 'field-agents',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Field Agents',
                'slug' => 'field-agents.create',
                'description' => 'Create new field agents',
                'module' => 'field-agents',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Field Agents',
                'slug' => 'field-agents.update',
                'description' => 'Edit existing field agents',
                'module' => 'field-agents',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Field Agents',
                'slug' => 'field-agents.delete',
                'description' => 'Delete field agents',
                'module' => 'field-agents',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Commission Disbursements Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Commission Disbursements',
                'slug' => 'commission-disbursements.view',
                'description' => 'View commission disbursements',
                'module' => 'commission-disbursements',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Commission Disbursements',
                'slug' => 'commission-disbursements.create',
                'description' => 'Create commission disbursement requests',
                'module' => 'commission-disbursements',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Approve Commission Disbursements',
                'slug' => 'commission-disbursements.approve',
                'description' => 'Approve commission disbursements',
                'module' => 'commission-disbursements',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Activity Logs Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Activity Logs',
                'slug' => 'activity-logs.view',
                'description' => 'View system activity logs',
                'module' => 'activity-logs',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Roles Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Roles',
                'slug' => 'roles.view',
                'description' => 'View list of roles',
                'module' => 'roles',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Create Roles',
                'slug' => 'roles.create',
                'description' => 'Create new roles',
                'module' => 'roles',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Roles',
                'slug' => 'roles.update',
                'description' => 'Edit existing roles',
                'module' => 'roles',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Delete Roles',
                'slug' => 'roles.delete',
                'description' => 'Delete roles',
                'module' => 'roles',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Profile Module
            [
                'id' => Str::uuid()->toString(),
                'name' => 'View Own Profile',
                'slug' => 'profile.view',
                'description' => 'View own profile',
                'module' => 'profile',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Update Own Profile',
                'slug' => 'profile.update',
                'description' => 'Update own profile information',
                'module' => 'profile',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('permissions')->insert($permissions);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('permissions')->truncate();
    }
};
