<?php

return [
    'default' => [
        'label' => 'Default',
        'primary' => '#006F78',
        'primary_dark' => '#005a62',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#6b7280',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'dark' => [
        'label' => 'Dark',
        'primary' => '#38bdf8',
        'primary_dark' => '#0ea5e9',
        'text_heading' => '#f8fafc',
        'text_body' => '#e2e8f0',
        'text_muted' => '#94a3b8',
        'bg_page' => '#0f172a',
        'bg_card' => '#1e293b',
        'bg_nav' => '#1e293b',
        'bg_input' => '#334155',
        'bg_hover' => '#334155',
        'border_color' => '#334155',
    ],
    'ocean' => [
        'label' => 'Ocean',
        'primary' => '#0d9488',
        'primary_dark' => '#0f766e',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#0f766e',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'indigo' => [
        'label' => 'Indigo',
        'primary' => '#6366f1',
        'primary_dark' => '#4f46e5',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#5b5b7a',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'rose' => [
        'label' => 'Rose',
        'primary' => '#f43f5e',
        'primary_dark' => '#e11d48',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#9f1239',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'emerald' => [
        'label' => 'Emerald',
        'primary' => '#10b981',
        'primary_dark' => '#059669',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#047857',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'amber' => [
        'label' => 'Amber',
        'primary' => '#f59e0b',
        'primary_dark' => '#d97706',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#b45309',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'violet' => [
        'label' => 'Violet',
        'primary' => '#8b5cf6',
        'primary_dark' => '#7c3aed',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#6d28d9',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'sky' => [
        'label' => 'Sky',
        'primary' => '#0ea5e9',
        'primary_dark' => '#0284c7',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#0369a1',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
    'slate' => [
        'label' => 'Slate',
        'primary' => '#475569',
        'primary_dark' => '#334155',
        'text_heading' => '#111827',
        'text_body' => '#1f2937',
        'text_muted' => '#475569',
        'bg_page' => '#f8fafc',
        'bg_card' => '#ffffff',
        'bg_nav' => '#ffffff',
        'bg_input' => '#f9fafb',
        'bg_hover' => '#f3f4f6',
        'border_color' => '#e5e7eb',
    ],
];
