package com.tajacore.distribution.ui.theme

import androidx.compose.ui.graphics.Color

// Professional palette: deep teal primary, clear hierarchy
val PrimaryLight = Color(0xFF0D7377)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF9FE7E9)
val OnPrimaryContainerLight = Color(0xFF002021)
val SecondaryLight = Color(0xFF4A6365)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8EA)
val OnSecondaryContainerLight = Color(0xFF051F21)
val TertiaryLight = Color(0xFF4D6163)
val OnTertiaryLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFF4FAFA)
val OnBackgroundLight = Color(0xFF171D1D)
val SurfaceLight = Color(0xFFF4FAFA)
val OnSurfaceLight = Color(0xFF171D1D)
val SurfaceVariantLight = Color(0xFFF4FAFA)
val OnSurfaceVariantLight = Color(0xFF171D1D)
val OutlineLight = Color(0xFF6F797A)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

val PrimaryDark = Color(0xFF5DD5DE)
val OnPrimaryDark = Color(0xFF00363B)
val PrimaryContainerDark = Color(0xFF004F54)
val OnPrimaryContainerDark = Color(0xFF9FE7E9)
val SecondaryDark = Color(0xFFB0CCCE)
val OnSecondaryDark = Color(0xFF1B3436)
val SecondaryContainerDark = Color(0xFF334B4D)
val OnSecondaryContainerDark = Color(0xFFCCE8EA)
val TertiaryDark = Color(0xFFB4C8CA)
val OnTertiaryDark = Color(0xFF1F3537)
val BackgroundDark = Color(0xFF0E1414)
val OnBackgroundDark = Color(0xFFE0E3E2)
val SurfaceDark = Color(0xFF0E1414)
val OnSurfaceDark = Color(0xFFE0E3E2)
val SurfaceVariantDark = Color(0xFF0E1414)
val OnSurfaceVariantDark = Color(0xFFE0E3E2)
val OutlineDark = Color(0xFF899294)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
